language: php
php:
  - "7.3"
  - "7.4"
before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - make dev
script:
  - make test
after_script:
  - php vendor/bin/php-coveralls -v
